name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js (kompatible Version für CoffeeScript 1.12.8)
        uses: actions/setup-node@v4
        with:
          node-version: '8'

      - name: Install CoffeeScript 1.12.8
        run: npm install -g coffeescript@1.12.8

      - name: Check CoffeeScript version
        run: coffee -v

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        shell: bash

      - name: Extract repository name
        run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
        shell: bash

      - name: Set zip file name
        run: echo "ZIP_NAME=customDataTypeDante.zip" >> $GITHUB_ENV

      - name: Build and Package
        shell: bash
        run: make zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: true
          generate_release_notes: true
          files: |
            build/${{ env.ZIP_NAME }}
            README.md
